---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/10/27 10:41
---

local cls = {
    res = "ui/ErrPanel",
}


function cls:init(params)
    local drawData = {
        btn0 = function()
            UI.close(self)
        end,
        btn1 = function()
            message:send("C2S_ThrowEx",{id=1},function()
                UI.showHint("抛出Actor异常成功");
            end)
        end,
        btn2 = function()
            message:send("C2S_ThrowEx",{id =2},function()
                UI.showHint("抛出Server异常成功");
            end)
        end,
        btn3 = function()
            message:send("C2S_ThrowEx",{id =3},function()
                UI.showHint("抛出数据存储异常成功");
            end)
        end
    }
    UI.draw(self.node,drawData)
end

return cls