---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/9/22 14:53
---

local cls = {
    res = "ui/Notice"
}

function cls:init(data)
    UI.button(self.node,"BtnClose",function()
        UI.close(self)
    end)
    self:show(data)
end

function cls:show(data)
    UI.text(self.node,"S/V/C/content",data.content)
    UI.text(self.node,"title",data.title)
end

return cls