---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/3 17:19
---
local cls = {
    res = "ui/unity_hall"
}
function cls:addRedDot(add)
    local btnJoinRequest = UI.child(self.node,"btnJoinRequest")
    local btnBuild = UI.child(self.node,"btnBuild")
    if add then
        RedDot.registerBtn(btnJoinRequest,RedDot.SystemID.UnityEnterReq,true)
        RedDot.registerBtn(btnBuild,RedDot.SystemID.UnityDailyBuild,true)
    else
        RedDot.unregisterBtn(btnJoinRequest,RedDot.SystemID.UnityEnterReq)
        RedDot.unregisterBtn(btnBuild,RedDot.SystemID.UnityDailyBuild)
    end
end

function cls:close()
    self:addRedDot(false)
    self.controller:close(self.controller.Pages.Hall)
end

function cls:init(info)
    self.controller = info.controller

    local btnData = {
        btnClose = function()
            self:close()
        end,
        btnBuild = function()
            self.controller:openPage(self.controller.Pages.Build)
        end,
        btnUnityInfo = function()
            self.controller:openPage(self.controller.Pages.UnityDetail)
        end,
        btnJoinRequest = function()
            self.controller:openPage(self.controller.Pages.UnityJoinRequest)
        end
    }

    UI.draw(self.node,btnData)
    self:update()
    self:addRedDot(true)
end

function cls:onFront()
    if self.controller.exitUnity then
        return
    end
    self:update()
end

function cls:update()
    message:send("C2S_openHall",{},function(msg)
        if msg.code == "ok" then
            local showRequest = msg.job == "SubLeader" or msg.job == "Leader"
            UI.enable(self.node,"btnJoinRequest",showRequest)
        else
            UI.showHint("联盟不存在!")
            self.controller:exit()
        end
    end)
end

return cls