---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/22 17:21
---
local cls = {
    res = "ui/unity_unityInfo"
}

function cls:close()
    self.controller:close(self.controller.Pages.UnityInfo)
end

---params S2C_requestUnity
function cls:init(info)
    self.controller = info.controller
    local params = info.params
    local data = {
        name = params.info.name,
        masterName = params.info.masterName,
        influence = params.info.influence,
        power = params.info.power,
        memberCount = params.info.memberCount,
        adv = params.info.adv,
        btnClose = function()
            self:close()
        end,
        btnJoin = function()
            self:join(params.info.id)
        end
    }

    UI.draw(self.node,data)

    UI.text(self.node,"name/level","LV."..params.info.lv)

    local requestJoin = true
    if params.data and params.data.requestJoinUnity
            and #params.data.requestJoinUnity > 0  then
        local list = params.data.requestJoinUnity
        local result =  table.find(list,function(a)
            if a == params.info.id then
                return a
            end
        end)

        if result ~=nil then
            requestJoin = false
        end
    end
    self.requestJoin = requestJoin
    self:showJoinBtnState(requestJoin)
end

function cls:showJoinBtnState(requestJoin)
    local text = requestJoin and "申请入盟" or "取消申请"
    UI.text(self.node,"btnJoin/Text",text);
end

function cls:join(targetId)
    if self.requestJoin then
        message:send("C2S_requestJoin",{id = targetId},function(msg)
            if msg.code == "playerHasUnity" then
                UI.msgBoxNoCloseBtn("提示","您已加入联盟，立刻前往联盟吧！",function()
                    self.controller:openPage(self.controller.Pages.Main)
                    self:close()
                end)
            elseif msg.code == "ok" then
                if msg.state == 1  then
                    UI.showHint("已发送申请")
                    self:showJoinBtnState(false)
                    self.requestJoin = false
                elseif msg.state == 2 then
                    UI.showHint("已取消申请")
                    self:showJoinBtnState(true)
                    self.requestJoin = true
                end
            elseif msg.code == "memberFull" then
                UI.showHint("该联盟成员已满")
                self:showJoinBtnState(false)
            end
        end)
    else
        message:send("C2S_cancelJoinReq",{id = targetId},function(msg)
            if msg.code == "ownUnity" then
                UI.msgBoxNoCloseBtn("提示","您已加入联盟，立刻前往联盟吧！",function()
                    self.controller:openPage(self.controller.Pages.Main)
                    self:close()
                end)
            else
                self:showJoinBtnState(true)
                self.requestJoin = true
            end
        end)
    end

end

return cls