---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/6 10:44
---
local cls = {
    res = "ui/unity_unityRank"
}

CS.Images.Load("Res/UnityRankIcon", "UnityRankIcon")

function cls:close()
    self.controller:close(self.controller.Pages.Rank)
end

function cls:init(params)
    self.controller = params.controller
    UI.button(self.node,"btnClose",function()
        self:close()
    end)
    self:update()
end

function cls:update()
    message:send("C2S_openUnityRank",{},function(msg)
        local parent = UI.child(self.node,"list/v/c")
        local count = msg.list and #msg.list or 0
        if msg.hasUnity then
            count = math.min(count,100)
        end
        UI.cloneChild(parent,count)
        UI.enable(self.node,"list/v/noUnity",count == 0)
        if count > 0  then
            for i = 1, count do
                local node = parent:GetChild(i-1)
                local data = msg.list[i]
                self:updateSingleItem(node,data,msg.hasUnity,i)
            end
        end
        self:updateMyInfo(msg)
    end)
end

function cls:updateSingleItem(node,data,hasUnity,index)
    print("alliance level:",data.level)
    if data.level == 0 then
        data.level =1
    end
    local memberMax = config["alliance"][data.level].memberMax
    print("排名：",index,"已经请：",data.hasRequest,"有联盟：",hasUnity,"用户数量：",data.member,"最大数量：",memberMax)
    local showBtnJoin = (not hasUnity) and (not data.hasRequest)
            and (data.member < memberMax)
    local showBtnCancel = (not hasUnity) and  data.hasRequest
            and (data.member < memberMax)

    local drawData = {
        level = "Lv."..data.level,
        name = data.name,
        rankNum = index,
        leader = data.leader,
        memberCount = data.member.."/"..memberMax,
        power = goldFormat(data.power),
        influence = goldFormat(data.influence),
        rank = index > 3 and 1 or index,
        btnJoin = function()
            message:send("C2S_requestJoin",{id = data.id},function(msg)
                self:dealWithRequestResult(msg,node,data,index,hasUnity,memberMax)
            end)
        end,
        btnCancel = function()
            message:send("C2S_cancelJoinReq",{id = data.id},function(msg)
                print("cancel msg:",msg.code)
                if msg.code =="ownUnity" then
                    UI.msgBoxNoCloseBtn("提示","您已加入联盟，立刻前往联盟吧！",function()
                        self.controller:openPage(self.controller.Pages.Main)
                        self:close()
                    end)
                else
                    data.hasRequest = false
                    self:updateSingleItem(node,data,false,index)
                end
            end)
        end
    }

    UI.draw(node,drawData)
    UI.enable(node,"btnJoin", showBtnJoin)
    UI.enable(node,"btnCancel", showBtnCancel)
    UI.enable(node,"mark", showBtnCancel)
    UI.enable(node,"rank",index < 4)
    UI.enable(node,"rankNum",index > 3)
end

function cls:dealWithRequestResult(msg,node,data,index,hasUnity,memberMax)
    if msg.code == "noUnity" then
        UI.showHint("该联盟已解散！")
        self:update()
    elseif msg.code == "memberFull" then
        UI.showHint("该联盟已满员！")
        data.member = memberMax
        self:updateSingleItem(node,data,hasUnity,index)
    elseif msg.code =="playerHasUnity" then
        UI.msgBoxNoCloseBtn("提示","您已加入联盟，立刻前往联盟吧！",function()
            self:openPage(self.Pages.Main)
            self:close()
        end)
    elseif msg.state == 1 then
        UI.showHint("申请成功")
        data.hasRequest = true
        self:updateSingleItem(node,data,hasUnity,index)
    elseif msg.state == 2 then
        UI.showHint("取消申请")
        data.hasRequest = false
        self:updateSingleItem(node,data,hasUnity,index)
    else
        UI.showHint("未知错误，请刷新页面")
        self:update()
    end
end

function cls:updateMyInfo(msg)
    local drawData = {
        name = msg.hasUnity and msg.unityName or "暂无",
        rank = msg.hasUnity and msg.unityRank or "暂无"
    }
    UI.draw(self.node,drawData)
end

return cls