---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/22 15:51
---
local cls = {
    res = "ui/unity_find"
}

function cls:close()
    self.controller:close(self.controller.Pages.Find)
end

local unityName = nil

function cls:init(data)
    self.controller = data.controller
    UI.button(self.node, "btnClose", function()
        self:close()
    end)
    UI.button(self.node, "btnSearch", function()
        self:search()
    end)
    local inputField = UI.child(self.node, "name")
                         .gameObject:GetComponent(typeof(CS.UnityEngine.UI.InputField))
    inputField.onValueChanged:AddListener(function(msg)
        unityName = msg
    end)
end

function cls:search()
    if unityName == nil then
        UI.showHint("请输入联盟ID")
    else
        message:send("C2S_requestUnity", { id = unityName }, function(msg)
            if msg.info == nil then
                UI.showHint("未查找到该联盟")
            else
                self:close()
                self.controller:openPage(self.controller.Pages.UnityInfo, msg)
            end
        end)
    end
    UI.text(self.node, "name", "")
    unityName = nil
end

return cls