---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/12 11:22
---
local cls = {
    res = "ui/unity_secretBoss"
}

function cls:close()
    self.controller:close(self.controller.Pages.SecretBoss)
end

function cls:onFront()
    if self.controller.exitUnity then
        return
    end
    self:show()
end

function cls:init(params)
    self.controller = params.controller
    UI.button(self.node,"btnClose",function()
        self:close()
    end)
    self:show()
end

function cls:show()
    message:send("C2S_showSecretList",{},function(msg)
        self:updateList(msg)
    end)
end

function cls:updateList(msg)
    self:dealWithCode(msg.code)
    local getSecretData = function(i, data)
        if data.list == nil then
            return nil
        else
            return data.list[i]
        end
    end

    if msg.code == "ok" then
        local parent = UI.child(self.node,"list/v/c")
        local secretConfig = config["allianceBarrier"]
        UI.cloneChild(parent,#secretConfig)
        for i = 1, #secretConfig do
            local tempConfig = secretConfig[i]
            local serverData = getSecretData(i,msg)
            self:updateBossItem(parent:GetChild(i-1),serverData,tempConfig,i)
        end
        local timeStr = convertToTime(msg.closeTime/1000)
        local str = timeStr.hour..":"..timeStr.minute..":"..timeStr.second
        UI.text(self.node,"time",str)
    end
end

function cls:updateBossItem(node,data,tempConfig,index)
    local getHpPercentage = function(totalHp, serverData)
        if serverData == nil then
            return 100
        else
            return  math.floor(serverData.crtHp/totalHp*100)
        end
    end

    local hpPer = getHpPercentage(tempConfig.life,data)
    local drawData = {
        blood = "血量：".. hpPer .."%",
        name = tempConfig.name,
        totalAttribute = "+"..tempConfig.devoteAll,
        exp = "+"..tempConfig.exp,
        influence = "+"..tempConfig.influence,
        tips = "联盟等级"..tempConfig.level.."开启",
        btnOpen = function()
            self:onBtnOpenClick(node,index,data)
        end,
        btnWait = function()
            self:onBtnWaitClick(node,index,data)
        end,
        btnEnter = function()
            self:onBtnEnterClick(node,index,data)
        end
    }

    local setItemState = function(state,crtHp)
        UI.enable(node,"timeCounter", crtHp > 0 and state == "opening")
        UI.enable(node,"tips",state == "lock")
        UI.enable(node,"btnOpen",state == "ready")
        UI.enable(node,"btnWait",state == "close")
        UI.enable(node,"btnEnter",crtHp > 0 and state == "opening")
        UI.enable(node,"killed",crtHp <=0 and state == "opening")
    end

    local slider = UI.component(node,"slider",typeof(CS.UnityEngine.UI.Slider))
    if slider then
        slider.value =  hpPer/100;
    end
    if data ~=nil then
        UI.txtUpdateTime(node,"timeCounter",data.crtTime/1000,function()
            setItemState("close",0)
        end)
    end
    UI.draw(node,drawData)

    if data == nil then
        setItemState("lock",1)
    else
        setItemState(data.state,data.crtHp)
    end


end

function cls:onBtnOpenClick(node,index,serverData)
    print("secret index:--------------",index)
    if serverData == nil then
        UI.showHint("秘境未解锁")
    else
        message:send("C2S_QueryCanOpenSecret",{secretId = index},function(msg)
            if msg.result == 0 then
                UI.showHint("无开启权限！")
            elseif msg.result == 1 then
                self.controller:openPage(self.controller.Pages.OpenSecret,serverData)
            elseif msg.result == 2 then
                UI.showHint("该联盟秘境已经开启")
            end
        end)
    end
end

function cls:onBtnWaitClick()
    UI.showHint("正在搜寻刑天，请等待")
end

function cls:onBtnEnterClick(node, index, serverData)
    if serverData == nil then
        UI.showHint("秘境未解锁")
    else
        message:send("C2S_enterSecret",{level = serverData.lv},function(msg)
            self:dealWithCode(msg.code)
            if msg.code == "ok" then
                self.controller:openPage(self.controller.Pages.SecretBattle,msg)
            elseif msg.code == "secretBossDead" then
                self:show()
            end
        end)
    end
end


function cls:dealWithCode(code,successMsg)
    local tip = successMsg
    local exit = false
    if code == "noUnity" then
        exit = true
        tip = "联盟数据不存在！"
    elseif code == "notMember" then
        exit = true
        tip = "您已不是联盟成员！"
    elseif code == "validSecretId" then
        tip = "无效的秘境ID，请退出重试"
    elseif  code == "secretHasClose" then
        tip = "秘境尚未开启"
    elseif code == "secretBossDead" then
        tip = "该秘境已被击败"
    elseif code == "secretHasUsed" then
        tip = "您已在其他联盟参与过此等级秘境，不可再次参与"
    end

    if tip ~= nil then
        UI.showHint(tip)
    end
    if exit then
        self.controller:exit()
    end
end

return cls