---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/4 13:29
---
local cls = {
    res = "ui/unity_changeJob"
}

function cls:close()
    self.controller:close(self.controller.Pages.ChangeUserJob)
end

function cls:init(params)
    self.controller = params.controller
    UI.button(self.node,"btnClose",function()
        self:close()
    end)

    self:update(params.params[1],params.params[2])
end

-- UnityMember
function cls:update(myJob,userData)
    message:send("C2S_openChangeJob",{id=userData.id},function(msg)
        local result = self:dealWithCode(msg.code)
        if not result then
            self:close()
            return
        end
        HeroTools.setHeadTemp(msg.userHeadId,userData.level,msg.userCloth)
        HeroTools.showAnim(self.node,"head",1)
        HeroTools.clearHeadTemp()
        local tempConfig = config["alliance"][msg.unityLevel]
        local drawData = {
            vipLv = userData.vipLevel,
            name = userData.name,
            power = userData.power,
            attribute = userData.attribute,
            num1 = msg.subLeaderCount.."/"..tempConfig.VP,
            num2 = msg.elitesCount.."/"..tempConfig.elite,
            num3 = msg.memberCount.."/"..(tempConfig.memberMax- tempConfig.elite - tempConfig.VP)
        }
        UI.draw(self.node,drawData)
        local canChangeMaster = myJob == "Leader" and userData.job == "SubLeader"
        local canKickOut = self:canKickOut(myJob,userData.job)
        UI.enable(self.node,"btnKickOut",canKickOut)
        UI.enable(self.node,"btnChangeMaster",canChangeMaster)
        if canKickOut then
            UI.button(self.node,"btnKickOut",function()
                self:kickOut(userData)
            end)
        end

        if canChangeMaster then
            UI.button(self.node,"btnChangeMaster",function()
                self:changeMaster(userData)
            end)
        end

        local showBtn1 = myJob == "Leader" and userData.job ~="SubLeader" and (msg.subLeaderCount< tempConfig.VP)
        local showBtn2 = userData.job ~= "Elites" and (msg.elitesCount<tempConfig.elite)
        local showBtn3 = userData.job ~= "Member"

        UI.enable(self.node,"btnPromote1",showBtn1)
        UI.enable(self.node,"btnPromote2",showBtn2)
        UI.enable(self.node,"btnPromote3",showBtn3)
        UI.button(self.node,"btnPromote1",function()
            self:changeUserJob(userData,2)
        end)
        UI.button(self.node,"btnPromote2",function()
            self:changeUserJob(userData,1)
        end)
        UI.button(self.node,"btnPromote3",function()
            self:changeUserJob(userData,0)
        end)

    end)
end

function cls:changeUserJob(userdata,newJob)
    message:send("C2S_changeUserJob",{id = userdata.id,newJob=newJob},function(msg)
       local isOk = self:dealWithCode(msg.code,"任命成功")
        if isOk then
            self:update(msg.myJob,msg.userData)
        else
            self:close()
        end
    end)
end

function cls:canKickOut(myJob,otherJob)
    if myJob == "Leader" then
        return true
    elseif myJob == "SubLeader" then
        return otherJob ~= "Leader" and otherJob ~="SubLeader"
    else
        return false
    end
end

function cls:kickOut(userdata)
    local msg = "是否将 "..userdata.name.."逐出联盟？"
    UI.msgBoxTitle("逐出联盟",msg,function()
        message:send("C2S_kickOut",{id = userdata.id},function(msg)
            self:dealWithCode(msg.code,"逐出成功")
            if msg.code == "ok" then
                self:close()
            end
        end)
    end,function()  end)
end

function cls:changeMaster(userData)
    local cost = config["allianceConfigure"][1].changeHeadcost
    local msg = "是否消耗".. cost .."联盟财富\n将联盟盟主职位移交给 ".. userData.name
    UI.msgBoxTitle("移交盟主",msg,function()
        message:send("C2S_changeLeader",{id=userData.id},function(msg)
            self:dealWithCode(msg.code)
            if msg.code == "ok" or msg.code == "noGold" then
                self:close()
                if msg.code == "ok" then
                    UI.showHint("移交盟主成功")
                end
            end
        end)
    end,function()
        print("不移交")
    end)
end

function cls:dealWithCode(code,successStr)
    local str
    if code == "noUser" then
        str = "无此用户"
    elseif code == "kickLeader" then
        str = "不可逐出盟主"
    elseif code == "noSubLeader" then
        str = "联盟没有副盟主，不可移交盟主权限"
    elseif code == "noAuthority" then
        str = "无任命权限"
    elseif code == "notMember" then
        str = "目标不属于联盟成员，不可任命"
    elseif code == "jobFull" then
        str = "当前职位人数已满"
    elseif code == "noGold" then
        str = "联盟财富不足"
    elseif code == "playerHasUnity" then
        str = "不在该联盟中"
    else
        str = successStr
    end
        if str then
        UI.showHint(str)
        end
        return code == "ok"
end

return cls;