---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/13 10:59
---

local cls = {
    res = "ui/unity_unityOpen"
}

function cls:close()
    self.controller:close(self.controller.Pages.OpenSecret)
end

function cls:init(params)
    self.controller = params.controller
    UI.button(self.node,"btnClose",function()
        self:close()
    end)
    self:show(params.params)
end


--params SecretLevelData
function cls:show(params)
    message:send("C2S_showOpenSecret",{level = params.lv},function(msg)
        self:dealWithCode(msg.code)
        if msg.code =="ok" then
            local tempConfig = config["allianceBarrier"][params.lv]
            local drawData = {
                tip = "开启".. tempConfig.name.."秘境",
                item1 = {
                    btnOpen = function()
                        self:openSecret(1,params.lv)
                    end,
                    crt = goldFormat(msg.wealth),
                    need = goldFormat(tempConfig.wealthCost)
                },
                item2 = {
                    btnOpen = function()
                        self:openSecret(0,params.lv)
                    end,
                    crt = goldFormat(msg.gold),
                    need = goldFormat(tempConfig.goldCost)
                }
            }

            UI.draw(self.node,drawData)
        end
    end)
end

function cls:openSecret(type,lv)
    message:send("C2S_openSecret",{secretId = lv,openType = type},function(msg)
        self:dealWithCode(msg.code,"开启成功")
        if msg.code == "secretHasOpen" then
            message:send("C2S_enterSecret",{level = lv},function(msg)
                self:dealWithCode(msg.code)
                if msg.code == "ok" then
                    self.controller:openPage(self.controller.Pages.SecretBattle,msg)
                elseif msg.code == "secretBossDead" then
                    self:close()
                end
            end)
        end

        if msg.code == "ok" then
            self:close()
        end
    end)
end

function cls:dealWithCode(code,successMsg)
    local tip = successMsg
    local exit = false
    if code == "noUnity" then
        exit = true
        tip = "联盟数据不存在！"
    elseif code == "notMember" then
        exit = true
        tip = "您已不是联盟成员！"
    elseif code == "validSecretId" then
        tip = "无效的秘境ID，请退出重试"
    elseif  code == "secretHasClose" then
        tip = "秘境已关闭"
    elseif code == "secretHasOpen" then
        tip = "秘境已开启，无需重复开启"
        self:close()
    elseif code == "noAuthority" then
        tip = "无联盟秘境开启权限"
        self:close()
    elseif code == "noGold" then
        tip = "元宝不足，可前往充值获得"
    elseif code == "noWealth" then
        tip = "联盟财富不足"
    end

    if tip ~= nil then
        UI.showHint(tip)
    end
    if exit then
        self.controller:exit()
    end
end

return cls