---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/9/3 11:04
---
local cls = {
    res = "ui/unity_entry"
}

function cls:close()
    self.controller:close(self.controller.Pages.Entry)
end

function cls:init(data)
    self.controller = data.controller
    self.controller:queryHasUnity(function()
        self:show()
    end)
end

function cls:show()
    local data = {
        btnClose = function()
            self:close()
        end,
        btnCreate = function()
            self.controller:queryHasUnity(function()
                self.controller:openPage(self.controller.Pages.Create)
            end)
        end,
        btnRandom = function()
            self.controller:queryHasUnity(function()
                self:randomJoin()
            end)
        end,
        btnSearch = function()
            self.controller:queryHasUnity(function()
                self.controller:openPage(self.controller.Pages.Find)
            end)
        end,
        btnFindRank = function()
            self.controller:queryHasUnity(function()
                self.controller:openPage(self.controller.Pages.Rank)
            end)
        end
    }
    UI.draw(self.node, data)
end

function cls:randomJoin()
    message:send("C2S_randomJoinUnity", {}, function(msg)
        if msg.success then
            self.controller:openPage(self.controller.Pages.Main)
        else
            UI.showHint("随机加盟失败！")
        end
    end)
end

return cls
