---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/5 14:25
---
local cls = {
    res = "ui/unity_changeName"
}

local unityNameLimitMin = 4
local unityNameLimitMax = 8

function cls:close()
    self.controller:close(self.controller.Pages.ChangeName)
end

function cls:init(params)
    self.controller = params.controller
    local tempConfig = config["allianceConfigure"][1].changeNameCost
    local drawData = {
        BtnClose = function()
            self:close()
        end,
        BtnCancel = function()
            self:close()
        end,
        BtnSure = function()
            local name = self.newName
            if name == nil or #name <= 0 then
                UI.showHint("请输入联盟名字")
                return
            end

            local hasSensitive, r1, r2 = Tools.sensitiveCheck(name)
            if hasSensitive then
                UI.showHint("联盟名字含有违禁词:" .. r2)
                return
            end

            local nameLen = Tools.getStrLenAsOne(name)
            if nameLen < unityNameLimitMin then
                UI.showHint("可输入" .. unityNameLimitMin .. "-" .. unityNameLimitMax .. "个字符")
                return
            end

            if nameLen > unityNameLimitMax then
                UI.showHint("可输入" .. unityNameLimitMin .. "-" .. unityNameLimitMax .. "个字符")
                return
            end

            message:send("C2S_changeUnityName",
                    { name = self.newName }, function(msg)
                        if msg.code == "noGold" then
                            UI.showHint("元宝不足，可前往充值获取")
                        elseif msg.code == "noAuthority" then
                            UI.showHint("没有改名权限")
                            self:close()
                        elseif msg.code == "noUnity" then
                            UI.showHint("联盟不存在!")
                            print("unity changeName--联盟不存在")
                            self.controller:exit()
                        elseif msg.code == "notMember" then
                            UI.showHint("不是联盟成员！")
                            self.controller:exit()
                        elseif msg.code == "nameExist" then
                            UI.showHint("名字重复！")
                        else
                            UI.showHint("修改成功")
                            self:close()
                        end
                    end)
        end,
        gold = tempConfig
    }

    UI.draw(self.node, drawData)

    local input = UI.component(self.node, "InputWord", typeof(CS.UnityEngine.UI.InputField))
    input.onValueChanged:AddListener(function(value)
        value = Tools.removeSymbolInString(value)
        local len = Tools.getStrLenAsOne(value)
        if len > unityNameLimitMax then
            value = Tools.subStringAsOne(value, unityNameLimitMax)
        end
        self.newName = value
        input.text = value
    end)
end

return cls