---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/5 13:12
---
local cls = {
    res = "ui/unity_detailInfo"
}

local contentLimit = 120

function cls:close()
    self.controller:close(self.controller.Pages.UnityDetail)
end

function cls:init(params)
    self.controller = params.controller

    UI.button(self.node, "btnClose", function()
        self:close()
    end)

    UI.button(self.node, "btnChange", function()
        self:changeUnityName()
    end)

    UI.button(self.node, "btns/btnDismiss", function()
        self:dismiss()
    end)

    UI.button(self.node, "btns/btnSave", function()
        self:changeUnityInfo()
    end)

    UI.button(self.node, "btns/btnQuit", function()
        self:quit()
    end)

    self:update()
end

function cls:onFront()
    if self.controller.exitUnity then
        return
    end
    self:update()
end

function cls:quit()
    UI.msgBoxTitle("提示", "退出联盟将减少50%的个人贡献", function()
        message:send("C2S_QuitUnity", {}, function(msg)
            if msg.success then
                UI.showHint("成功退出联盟")
                self.controller:exit()
            else
                if msg.code == "onRushLoop" then
                    UI.showHint("联盟冲榜活动期间，无法退出联盟。")
                else
                    UI.showHint("退出失败!")
                end
            end
        end)
    end, function()

    end)
end

function cls:changeUnityName()
    if self.data == nil or self.data.myJob == "Member"
            or self.data.myJob == "Elites" then
        UI.showHint("暂无权限！")
        return
    end
    self.controller:openPage(self.controller.Pages.ChangeName, self.data)
end

function cls:dismiss()
    if self.data == nil or self.data.myJob ~= "Leader" then
        UI.showHint("暂无权限！")
        return
    end

    local node = UI.showNode(self.node, "ui/unity_dismiss")
    UI.button(node, "BtnClose", function()
        UI.close(node)
    end)
    UI.button(node, "BtnYes", function()
        message:send("C2S_dismissUnity", { unityId = self.data.id }, function(msg)
            local result = self:dealWithCode(msg.code)
            print("err code:", msg.code)
            UI.close(node)
            if result then
                self.controller:exit()
            end
        end)
    end)

    UI.enable(node, "BtnYes", false)
    UI.txtUpdateTime(node, "time", 30, function()
        UI.enable(node, "BtnYes", true)
    end)
end

function cls:changeUnityInfo()
    UI.enable(self.node, "noticeLimit", false)
    UI.enable(self.node, "advLimit", false)
    message:send("C2S_changeUnityInfo",
            { adv = self.advStr, notice = self.noticeStr },
            function(msg)
                local result = self:dealWithCode(msg.code, "修改成功")
                if not result then
                    self:close()
                end
            end)
end

function cls:update()
    message:send("C2S_openDetails", {}, function(msg)
        local result = self:dealWithCode(msg.code)
        if not result then
            self:close()
            return
        end

        self.data = msg
        local unityConfig = config["alliance"][msg.level]
        local drawData = {
            name = msg.unityName,
            master = msg.leaderName,
            level = msg.level,
            exp = msg.exp,
            influence = msg.influence,
            rich = msg.wealth,
            power = msg.power,
            member = msg.memberCount .. "/" .. unityConfig.memberMax,
            id = msg.id
        }
        UI.draw(self.node, drawData)

        local showDismissUnity = msg.myJob == "Leader"
        local showChangeInfo = msg.myJob == "SubLeader" or showDismissUnity
        local showQuit = msg.myJob ~= "Leader"
        UI.enable(self.node, "btns/btnDismiss", showDismissUnity)
        UI.enable(self.node, "btnChange", showDismissUnity)
        UI.enable(self.node, "btns/btnQuit", showQuit)
        UI.enable(self.node, "noticeLimit", false)
        UI.enable(self.node, "advLimit", false)
        UI.enable(self.node, "btns/btnSave", showChangeInfo)
        local noticeInputField = UI.component(self.node, "noticeInputField", typeof(CS.UnityEngine.UI.InputField))
        local advInputField = UI.component(self.node, "advInputField", typeof(CS.UnityEngine.UI.InputField))
        noticeInputField.text = msg.notice
        advInputField.text = msg.adv
        self.advStr = msg.adv
        self.noticeStr = msg.notice
        noticeInputField.interactable = showChangeInfo
        advInputField.interactable = showChangeInfo

        if showChangeInfo then
            noticeInputField.onValueChanged:AddListener(function(value)
                UI.enable(self.node, "noticeLimit", true)
                local hasSensitive, result = Tools.sensitiveCheck(value)
                local len = Tools.getStrLen(result)
                if len > contentLimit then
                    result = Tools.subString(result, contentLimit)
                end
                noticeInputField.text = result
                UI.text(self.node, "noticeLimit", Tools.getStrLen(result) .. "/120")
                self.noticeStr = result
            end)
            advInputField.onValueChanged:AddListener(function(value)
                local hasSensitive, result = Tools.sensitiveCheck(value)
                UI.enable(self.node, "advLimit", true)
                local len = Tools.getStrLen(result)
                if len > contentLimit then
                    result = Tools.subString(result, contentLimit)
                end
                advInputField.text = result
                UI.text(self.node, "advLimit", Tools.getStrLen(result) .. "/120")
                self.advStr = result
            end)
        end
    end)
end

function cls:dealWithCode(code, successStr)
    local str
    if code == "noUnity" then
        str = "联盟不存在"
    elseif code == "noAuthority" then
        str = "没有权限"
    elseif code == "notMember" then
        str = "不是联盟成员"
    elseif code == "noUser" then
        str = "用户不存在"
    elseif code == "onRushLoop" then
        str = "联盟冲榜活动期间，无法解散联盟。"
    else
        str = successStr
    end
    if str then
        UI.showHint(str)
    end
    return code == "ok"
end

return cls


