---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/19 18:02
---
local cls = {
    res = "ui/unity_NobleBuff"
}

function cls:close()
    self.controller:close(self.controller.Pages.RichAdd)
end

function cls:init(data)
    self.controller = data.controller
    UI.button(self.node, "btnClose", function()
        self:close()
    end)
    self:show()
end

function cls:show()
    message:send("C2S_queryMyNoble", {}, function(msg)
        local exit, close = self:dealWithCode(msg.code)
        if exit or close then
            return
        end

        local list = msg.nobleList
        local count = list == nil and 0 or #list
        local parent = UI.child(self.node, "list")
        UI.cloneChild(parent, count)
        UI.enable(parent, count > 0)
        UI.enable(self.node, "nobody", count <= 0)
        if count > 0 then
            for i = 1, #list do
                local item = parent:GetChild(i - 1)
                local data = list[i]
                self:updateListItem(item, data)
            end
        end
    end)
end

function cls:updateListItem(node, id)
    print("node name:", node.name, id)
    local tempConfig = config["allianceNoble"][id]
    if tempConfig then
        local drawData = {
            icon = id,
            name = tempConfig.name,
        }
        UI.draw(node, drawData)
        local buffList = self:getDescList(tempConfig)
        local count = #buffList
        local buffParent = UI.child(node, "list")
        UI.cloneChild(buffParent, count)
        if count > 0 then
            for i = 1, count do
                UI.text(buffParent:GetChild(i - 1), buffList[i])
            end
        end
    else
        print("no config for:", id)
    end
end

function cls:dealWithCode(code, successMsg, failMsg)
    local tip = successMsg
    local exit = false
    local close = false
    if code == "noUnity" then
        exit = true
        tip = "联盟数据不存在！"
    elseif code == "notMember" then
        exit = true
        tip = "您已不是联盟成员！"
    elseif code == "noAuthority" then
        tip = "暂无权限！"
    elseif code == "validNobleId" then
        tip = "权贵Id错误 ，请退出重试"
        close = true
    elseif code == "fail" then
        tip = failMsg == nil and "数据错误，请重新打开界面" or failMsg
    elseif code == "error_noDrawNum" then
        tip = "拉拢次数已耗完"
    elseif code == "error_noTime" then
        tip = "该权贵处于保护状态，不可拉拢"
    elseif code == "alreadyInUnity" then
        tip = "该权贵已加入联盟，无需再次拉拢"
    end

    if tip ~= nil then
        UI.showHint(tip)
    end
    if exit then
        self.controller:exit()
    elseif close then
        self:close()
    end

    return exit, close
end

function cls:getDescList(tempConfig)
    local result = {}

    if tempConfig and tempConfig.businessPercent > 0 then
        table.insert(result, "商业收益提升: +" .. tempConfig.businessPercent * 100 / 10000 .. "%")
        print("result：", tempConfig.businessPercent / 10000)
    end

    if tempConfig and tempConfig.farmPercent > 0 then
        table.insert(result, "农业收益提升: +" .. tempConfig.farmPercent * 100 / 10000 .. "%")
    end

    if tempConfig and tempConfig.recruitPercent > 0 then
        table.insert(result, "征兵收益提升: +" .. tempConfig.recruitPercent * 100 / 10000 .. "%")
    end

    if tempConfig and tempConfig.waterBattleDamage > 0 then
        table.insert(result, "议政伤害提升: +" .. tempConfig.waterBattleDamage * 100 / 10000 .. "%")
    end

    return result
end

return cls
