---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/2 10:06
---
local class = {
}

local controller = nil

---@param ctr [catchAssailant]
function class:init(root,ctr)
    self.root = root
    controller = ctr
    local param = {
        btnClose = function()
            controller:close()
        end,
        btnHelp = function()
            controller:openPage(controller.Pages.HelpPage)
        end,
        btnRank = function()
            controller:openPage(controller.Pages.RankPage)
        end,
        btnScore = function()
            controller:openPage(controller.Pages.ScorePage)
        end,
        btnStart = function()
            controller:enterGame()
        end,
        animRoot = 2
    }
    UI.draw(self.root,param)
end

---@param show boolean
---@param searchTimeStr string
---@param catchTimeStr string
---@param waitTime number 秒
function class:show(show)
    UI.enable(self.root,show)
    if show then
       message:send("C2S_GetTime",{},function(msg)
           self:onGetTimeMsg(msg)
       end)
    end
end

-- msg:S2C_GetTime
function class:onGetTimeMsg(msg)
    if msg.code == "configError" then
        UI.msgBoxTitle("提示","配置错误，请联系客服！",function()
            controller:close()
        end)
    else
        local searchStart =  convertToTime(msg.searchStartTime/1000)
        local searchEnd = convertToTime(msg.searchEndTime/1000)
        local catchStart = convertToTime(msg.catchStartTime/1000)
        local catchEnd = convertToTime(msg.catchEndTime/1000)
        local searchEnd = convertToTime(msg.searchEndTime/1000)
        local waitTime = msg.waitTime
        local data = {
            searchTime = "每日"..self:getTimeStr(searchStart).."-"..self:getTimeStr(searchEnd),
            catchTime = "每日"..self:getTimeStr(catchStart).."-"..self:getTimeStr(catchEnd)
        }
        UI.draw(self.root,data)
        self:showWaitOrStart(waitTime)
    end
end

function class:getTimeStr(times)
    local result = ""
    local temp = function(value,str,addSeparation)
        str = str..value
        if addSeparation then
            str = str..":"
        end
        return str
    end

    print("times:",times.hour,times.minute,times.second)
    result = temp(times.hour,result,true)
    result = temp(times.minute,result,true)
    result = temp(times.second,result,false)
    return result
end

function class:showWaitOrStart(waitTime)
    UI.enable(self.root,"waitTime",waitTime >0)
    UI.enable(self.root,"waitImg",waitTime >0)
    UI.enable(self.root,"btnStart",waitTime <=0)
    if waitTime >0 then
        UI.txtUpdateTime(self.root,"waitTime",waitTime/1000,function()
            self:show(true)
        end)
    end
end

return class
