---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/5 11:14
---
local class = {
}



local controller = nil

---@param ctr [catchAssailant]
function class:init(root,ctr)
    self.root = root
    controller = ctr
    UI.button(root,"btnClose",function()
        self:show(false)
    end)
end

function class:show(show)
    UI.enable(self.root,show)
    if show then
        message:send("C2S_getExchangeInfo",{},function(msg)
            self.pageData = msg
            local config = config["item"]
            local items = msg.items
            local parent = UI.child(self.root,"list/v/c")
            UI.cloneChild(parent,#items)
            for i = 1, #items do
                self:showSingleItem(items[i],config,parent,i)
            end

            UI.text(self.root,"myScore",msg.myScore)
        end)
    end
end

-- data:ExchangeItem
-- itemConfig:Item配置表
-- parent：scroll view 的content层级
-- index: 当前显示数据在列表中的排序index
function class:showSingleItem(data, itemConfig,parent,index)
    local itemConfig = table.find(itemConfig,function(a)
        if a.id == data.id then
            return a
        end
    end)

    local exChangeConfig = table.find(config["worldBossChange"],function(a)
        if a.itemID == data.id then
            return a
        end
    end)

    local drawData = {
        name = itemConfig.name,
        cost = exChangeConfig.costPoint,
        btnExchange = function()
            self:onExchangeBtnClick(data.id,index)
        end,
        icon = itemConfig.icon,
        lastCount = data.count,
        btnDesc = data.count > 0 and "兑换" or "售罄"
    }

    local transItem = parent:GetChild(index-1)
    UI.draw(transItem,drawData)
    UI.button(transItem,"icon",function()
        self:onItemClick(data.id)
    end)

    local btn = UI.child(transItem,"btnExchange").gameObject:GetComponent(
            typeof(CS.UnityEngine.UI.Button)
    )

    if data.count >0 then
        btn.enabled = true
        UI.clearGray(transItem,"btnExchange")
    else
        btn.enabled = false
        UI.setGray(transItem,"btnExchange")
    end
end

function class:onItemClick(id)
    UI.showItemInfo(id)
end

function class:onExchangeBtnClick(id,index)
    self.crtExchangeId = id
    self.crtExchangeIndex = index
    message:send("C2S_exchange",{id=id,index = index},function(msg)
        self:dealWithErrorCode(msg.code)
        if msg.code == "ok" then
            local config = config["item"][msg.id]
            ItemTools.showItemResult({
                name = config.name,
                icon = config.icon,
                count = 1
            })
            self:updateSingleItem(msg)
        end
    end)
end

--msg:S2C_exchange
function class:updateSingleItem(msg)
    if msg.id ~= self.crtExchangeId or msg.index ~= self.crtExchangeIndex then
        log_call("exchange error！value not match,local id:"..self.crtExchangeId..",index："..self.crtExchangeIndex)
        log_call("server id:"..msg.id..",server index:"..msg.index)
    end
    local parent = UI.child(self.root,"list/v/c")
    UI.text(self.root,"myScore",msg.myScore)
    self:showSingleItem(msg.item,config["item"],parent,msg.index)
end

function class:dealWithErrorCode(code)
    if code =="ok" then
        return
    elseif code =="configError" then
        UI.showHint("配置错误")
    elseif code =="noCount" then
        UI.showHint("道具数量不足，无法兑换")
    elseif code =="noScore" then
        UI.showHint("积分不足，无法兑换")
    end

end

return class
