---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/6 10:42
---

local class = {
}

local controller = nil
CS.Images.Load("Res/Clue","Clue")

---@param ctr [catchAssailant]
function class:init(root,ctr)
    self.root = root
    controller = ctr
    UI.button(self.root,"btnClose",function()
        self:show(false)
    end)
    self:showFindKeyMan(false)
    self:showFindClue(false)
end


---@param searchedIndex table 
function class:showScene(sceneId,searchedIndex)
    for i = 1, 4 do
        UI.enable(self.root,"scene"..i,sceneId == i)
    end

    local btnPath = "scene"..sceneId.."/btn"
    for i = 1, 3 do
        local btn = UI.child(self.root,btnPath..i)
        UI.enable(btn,true)
        UI.button(btn,function()
            self:onSceneBtnClick(i)
            UI.enable(btn,false)
        end)
    end

    if searchedIndex and #searchedIndex>0 then
        for i, v in ipairs(searchedIndex) do
            UI.enable(self.root,btnPath ..v,false)
        end
    end
    self:showDialog()
end

function class:showDialog()
    UI.enable(self.root,"npc",true)
    local data = {
        dialog = self:randomTalk(1),
        animRoot = 2
    }
    UI.draw(self.root,"npc",data)
    UI.delay(self.root,5,function()
        UI.enable(self.root,"npc",false)
        UI.enable(self.root,"tip",true)
    end)

end

function class:randomTalk(type)
    local config = config["worldBossDetectTalk"]
    local list = {}
    local count = 0
    for i, v in ipairs(config) do
        if v.type == type then
            count = count+1
            list[count] = v
        end
    end

    local random = math.floor(math.random(1,count))
    return list[random]
end

function class:onSceneBtnClick(index)
    message:send("C2S_search",{index =index},function(msg)
        local isOk = controller:dealWithCode(msg.code)
        if isOk then
            local config = config["worldBossDetectAffair"][msg.clueId]
            if config.type == 1 then
                self:showFindClue(true,msg.clueId)
            elseif config.type ==2 then
                self:showFindKeyMan(true,msg.clueId)
            else
                log_call("unknow clue type:"..config.type)
            end
        end
    end)
end

--msg:Search
function class:show(show,msg)
    UI.enable(self.root,show)
    if show then
        UI.enable(self.root,"tip",false)
        --self:showScene(sceneId)
        local levelConfig = config["worldBossDetect"][msg.id]
        self:showScene(levelConfig.scene,msg.searchedIndex)
        if msg.keyManId >0 then
            self:showFindKeyMan(true,msg.keyManId)
        end
    end
end

function class:showFindClue(show,id)
    UI.enable(self.root,"findClue",show)
    if show then
        local config = config["worldBossDetectAffair"][id]
        print("img.."..config.pic)
        local data = {
            btnSure = function()
                self:showFindClue(false)
            end,
            count = "+"..config.point,
            dialog = config.description,
            icon = config.pic
        }
        UI.draw(self.root,"findClue",data)
    end
end

function class:showFindKeyMan(show,id)
    UI.enable(self.root,"findKeyMan",show)
    if show then
        local tempConfig = config["worldBossDetectAffair"][id]
        local data = {
            btnFight = function()
                self:showFindKeyMan(false)
                controller:openPage(controller.Pages.FightKeyMan)
            end,
            count = tempConfig.point,
            dialog = tempConfig.description,
            icon = 1
        }
        UI.draw(self.root,"findKeyMan",data)
    end
end


return class