---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/2 10:01

---@Class catchAssailant
local Class = {
    res = "UI/baiYeJiXiong"
}

Class.Pages = {
    HelpPage = 1,
    ScorePage = 2,
    RankPage = 3,
    SearchPage = 4,
    FightBossPage = 5,
    FightKeyMan = 6,
    EntryPage = 7
}

Class.PageInstance = {}


local entryPage = require("game.outdoor.catchAssailant.entry")
local helpPage = require("game.outdoor.catchAssailant.help")
local rankPage = require("game.outdoor.catchAssailant.rank")
local exchangePage =require("game.outdoor.catchAssailant.exchange")
local searchPage = require("game.outdoor.catchAssailant.search")
local fightKeyManPage = require("game.outdoor.catchAssailant.fightKeyMan")
local bossPage = require("game.outdoor.catchAssailant.boss")
function Class:init()
    self.hasClose =false
    entryPage:init(UI.child(self.node,"entry"),self)
    entryPage:show(true)
    self:addPage(entryPage,self.Pages.EntryPage)

    helpPage:init(UI.child(self.node,"help"),self)
    helpPage:show(false)
    self:addPage(helpPage,self.Pages.HelpPage)

    rankPage:init(UI.child(self.node,"rank"),self)
    self:addPage(rankPage,self.Pages.RankPage)
    rankPage:show(false)

    exchangePage:init(UI.child(self.node,"exchange"),self)
    self:addPage(exchangePage,self.Pages.ScorePage)
    exchangePage:show(false)

    searchPage:init(UI.child(self.node,"search"),self)
    self:addPage(searchPage,self.Pages.SearchPage)
    searchPage:show(false)

    fightKeyManPage:init(UI.child(self.node,"fightKeyMan"),self)
    self:addPage(fightKeyManPage,self.Pages.FightKeyMan)
    fightKeyManPage:show(false)

    bossPage:init(UI.child(self.node,"boss"),self)
    self:addPage(bossPage,self.Pages.FightBossPage)
    bossPage:show(false)

    CS.Sound.PlayMusic("music/worldboss")
end

function Class:addPage(cls,pageIndex)
    self.PageInstance[pageIndex] = cls
end

function Class:openPage(index,param)
    local page = self.PageInstance[index]
    if page and page.show then
        page:show(true,param)
    else
        log_call(" cant show page:"..index)
    end
end

function Class:close()
    self.hasClose = true
    UI.close(self)
end

function Class:enterGame(callback)
    message:send("C2S_catchAssailant", {}, function(msg)
        if self.hasClose  then
            return
        end
        if msg.state == 0 then
            UI.showHint("暂未开放")
            entryPage:showWaitOrStart(msg.waitTime)
        elseif msg.state == 1 then
            if msg.search.keyManId > 0 then
                self:openPage(self.Pages.FightKeyMan)
            else
                self:openPage(self.Pages.SearchPage, msg.search)
            end
        elseif msg.state == 2 then
            self:openPage(self.Pages.FightBossPage, msg.fight)
        elseif msg.state == 3 then
            self:openPage(self.Pages.EntryPage)
        end
        if callback then
            callback()
        end
    end)
end


local errorCode = {
    ok = "ok",
    configError = "configError",
    noCount = "noCount",
    noScore = "noScore",
    searchComplete = "searchComplete",
    repeatIndex = "repeatIndex",
    notSearchTime = "notSearchTime",
    notCatchTime = "notCatchTime"
}
function Class:dealWithCode(code)
    if code == errorCode.ok  then
        return true
    elseif code == errorCode.configError then
        UI.showHint("配置错误，请检查配置")
    elseif code == errorCode.noCount then
        UI.showHint("道具数量不足，无法兑换")
    elseif code == errorCode.noScore then
        UI.showHint("积分不足，无法兑换")
    elseif code == errorCode.searchComplete then
        UI.showHint("侦查已结束")
        self:backToEntry()
    elseif code ==errorCode.repeatIndex then
        UI.showHint("该区域已经被搜查过了")
    elseif code == errorCode.notSearchTime then
        UI.showHint("侦查时间结束")
        self:backToEntry()
    elseif code == errorCode.notCatchTime then
        UI.showHint("缉凶时间结束")
        self:backToEntry()
    end
    return false;
end

function Class:backToEntry()
    helpPage:show(false)
    rankPage:show(false)
    exchangePage:show(false)
    searchPage:show(false)
    fightKeyManPage:show(false)
    bossPage:show(false)
    entryPage:show(true)
end


return Class