---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/21 16:02
---
local cls = {
    res = "ui/unity_empty"
}

cls.Pages = {
    Main = "game.outdoor.unity.unityMain",
    Create = "game.outdoor.unity.unityCreate",
    Rank = "game.outdoor.unity.unityRank",
    Secret = "game.outdoor.unity.unitySecretBoss",
    Member = "game.outdoor.unity.unityMember",
    Rich = "game.outdoor.unity.unity_noble",
    Hall = "game.outdoor.unity.unityHall",
    Shop = "game.outdoor.unity.unityShop",
    RichAdd = "game.outdoor.unity.unityNobleBuff",
    Find = "game.outdoor.unity.unityFind",
    UnityInfo = "game.outdoor.unity.unityInfo",
    UnityJoinRequest = "game.outdoor.unity.unityJoinRequest",
    Build = "game.outdoor.unity.unityBuild",
    UnityDetail = "game.outdoor.unity.unityDetail",
    ChangeUserJob = "game.outdoor.unity.unityChangeJob",
    ChangeName = "game.outdoor.unity.unityChangeName",
    OpenSecret = "game.outdoor.unity.unityOpenSecret",
    SecretBoss = "game.outdoor.unity.unitySecretBoss",
    SecretBattle = "game.outdoor.unity.unityBattle",
    ChangeHeroes = "game.outdoor.unity.unityChangeHeroes",
    Entry = "game.outdoor.unity.unityEntry"
}

function cls:init()
    self.hasClose = false
    self.pageCount = 0
    message:send("C2S_getMyUnityInfo", {}, function(msg)
        if self.hasClose then
            return
        end
        if msg.info == nil then
            self:openPage(self.Pages.Entry)
        else
            self:openPage(self.Pages.Main, msg.info)
        end
    end)
end

function cls:openPage(page, params)
    if page == nil or page == "" then
        UI.showHint("找不到对应页面!")
        return
    end

    print("打开页面：",self.pageStack == nil,page)
    if self.pageStack == nil then
        self.pageStack = {}
        self.pageIndex = {}
    end

    if self.pageStack[page] ~= nil then
        print(self.node.name,"已经显示过了~:",page)
        for i, v in pairs(self.pageStack) do
            print("已经存在的页面：",i)
        end
        return
    end
    local data = {}
    data.controller = self
    data.params = params
    local result = UI.show(page, data)
    self.pageStack[page] = result
    table.insert(self.pageIndex,#self.pageIndex+1,page)
    self.pageCount = self.pageCount +1
end

function cls:close(page)
    if self.pageStack and self.pageStack[page] then
        UI.close(self.pageStack[page])
        self.pageStack[page] = nil
        for i = 1, #self.pageIndex do
            if self.pageIndex[i]==page then
                table.remove(self.pageIndex,i)
                break;
            end
        end
        self.pageCount = self.pageCount -1
        if self.pageCount == 0 then
            self.hasClose = true
            UI.close(self)
        end
    end
end

function cls:exit()
    if self.pageStack == nil then
        return
    end
    self.exitUnity = true
    if self.pageStack and #self.pageIndex > 0 then
        for i = #self.pageIndex, 1,-1 do
            if self.pageStack[self.pageIndex[i]] then
                UI.close( self.pageStack[self.pageIndex[i]])
            end
        end
    end
    self.pageStack = nil
    self.pageIndex = nil
    self.hasClose = true
    UI.close(self)
    self.exitUnity = false
end

function cls:queryHasUnity(failCallback)
    message:send("C2S_QueryUnity",{},function(msg)
        if self.hasClose then
            return
        end
        if msg.result then
            UI.msgBoxNoCloseBtn("提示","您已加入联盟，立刻前往联盟吧！",function()
                self:openPage(self.Pages.Main)
            end)
        else
            if failCallback ~= nil then
                failCallback()
            end
        end
    end)
end


return cls
