return {
	{
		id=1,
		name="1.比词招亲",
		story="穿越到一个陌生的世界，凭借脑海中的知识赢得美人的芳心。",
		storyPic=1,
		background=1
	},
	{
		id=2,
		name="2.桃花宴",
		story="比鸿门宴更可怕的是桃花宴，美人在怀，能有多少人是柳下惠啊。",
		storyPic=2,
		background=2
	},
	{
		id=3,
		name="3.灭黑狗帮",
		story="黑帮暗藏大量来历不明的黄金，似乎卷进了什么不得了的事情当中。",
		storyPic=3,
		background=3
	},
	{
		id=4,
		name="4.公孙娘子",
		story="一个小小县城中，光鲜之下藏污纳垢不忍直视。",
		storyPic=1,
		background=1
	},
	{
		id=5,
		name="5.引蛇出洞",
		story="不要轻视你的任何一个对手，我对褒姒这么说道，却忘了对自己说。",
		storyPic=2,
		background=2
	},
	{
		id=6,
		name="6.劫狱",
		story="草菅人命的大喊仁义，贪赃枉法的标榜名誉，这个世界的三观都崩坏了。",
		storyPic=3,
		background=3
	},
	{
		id=7,
		name="7.突发事件",
		story="光天化日，射箭送信，我是要正面对上真正的凶人了。",
		storyPic=1,
		background=1
	},
	{
		id=8,
		name="8.威胁",
		story="潘金莲写了一封恐吓信，一个山贼头领居然威胁朝廷命官？",
		storyPic=2,
		background=2
	},
	{
		id=9,
		name="9.千户所",
		story="剿匪需找千户大人寻求帮助，但这么破破烂烂的院子居然是千户所？",
		storyPic=3,
		background=3
	},
	{
		id=10,
		name="10.余千户",
		story="余千户是一位视军令如生命的好将军，但是不是有点过于迂腐了？",
		storyPic=1,
		background=1
	},
	{
		id=11,
		name="11.陈圆圆",
		story="万万没想到陈圆圆不仅是霸道女总裁，还是慷慨的女财神。",
		storyPic=2,
		background=2
	},
	{
		id=12,
		name="12.再会",
		story="原来是钱啊！得陈圆圆指点，我带着大量钱财来找余千户，这次不拒绝了吧？",
		storyPic=3,
		background=3
	},
	{
		id=13,
		name="13.入虎穴",
		story="乔装打扮一番，我们来到玄蜂山玄蜂寨，怎么着也要先见见下一个要对付的是啥样的人啊！",
		storyPic=1,
		background=1
	},
	{
		id=14,
		name="14.陈近南",
		story="山贼陈近南？你跟那个大侠陈近南是什么关系？算了这不重要……一起对付潘金莲？这个可以有。",
		storyPic=2,
		background=2
	},
	{
		id=15,
		name="15.反间",
		story="达成合作的效果立马就出来了，陈近南给传递了不少玄蜂寨的消息。",
		storyPic=3,
		background=3
	},
	{
		id=16,
		name="16.密谋",
		story="进攻的号角吹响！如此如此，这般这般，定然万无一失！",
		storyPic=1,
		background=1
	},
	{
		id=17,
		name="17.擒拿潘金莲",
		story="为什么都不按剧本走呢？偏要多费一番周折。算了，潘金莲被擒，心里一口恶气……额，终于为民除害了！",
		storyPic=2,
		background=2
	},
	{
		id=18,
		name="18.清理",
		story="大破玄蜂寨，可以欢天喜地的查抄了。可是感觉有点不对……所以说，余千户你到底搜出了什么啊？",
		storyPic=3,
		background=3
	},
	{
		id=19,
		name="19.蹊跷",
		story="到处都透着蹊跷，尤其是商人陈圆圆，看来得好好调查一下了。",
		storyPic=1,
		background=1
	},
	{
		id=20,
		name="20.流民",
		story="最近很多灾民涌入，杨府在城南施粥，正好去看看，都是要关注的问题。",
		storyPic=2,
		background=2
	},
	{
		id=21,
		name="21.杨府晚宴",
		story="陈圆圆设宴款待，这么好的调查机会当然要把握住了。等等，为什么一直灌我酒啊？",
		storyPic=3,
		background=3
	},
	{
		id=22,
		name="22.红拂",
		story="红拂姑娘皮肤好白啊，请问是怎么保养的呢？没有别的意思啊，真的！我就问问。",
		storyPic=1,
		background=1
	},
	{
		id=23,
		name="23.夜会",
		story="有黑衣人？这种事不重要啦，红拂姑娘在投怀送抱，哦不对，有要事禀报，我们在讨论严肃的事情。",
		storyPic=2,
		background=2
	},
	{
		id=24,
		name="24.旖旎",
		story="本官很生气，没看到本官……和红拂姑娘在床上探讨大事呢？推门而入想干嘛？",
		storyPic=3,
		background=3
	},
	{
		id=25,
		name="25.行动",
		story="杨府派了黑衣人，原来是去找佛经的。佛经还要这么郑重其事的找？其中必有蹊跷。",
		storyPic=1,
		background=1
	},
	{
		id=26,
		name="26.绸缪",
		story="要针对杨府做些布置了啊……红拂姑娘这么巧？看雨那？我陪你啊？",
		storyPic=2,
		background=2
	},
	{
		id=27,
		name="27.杀手",
		story="《佛说四十二章经》？左看右看也只是一本普通的佛经啊……干嘛推我？有杀手啊，有杀手？",
		storyPic=3,
		background=3
	},
	{
		id=28,
		name="28.荆轲",
		story="这个杀手……忽悠过来先，不然不放心啊。",
		storyPic=1,
		background=1
	},
	{
		id=29,
		name="29.宝藏传闻",
		story="听了个有些狗血的宝藏传闻，总感觉在哪里听过？也许吧。",
		storyPic=2,
		background=2
	},
	{
		id=30,
		name="30.白玉堂",
		story="是不是哪里弄错了？盗帅不是那个谁谁谁吗？咋变成了白玉堂？好吧，总之，想拿经书，问过我没有？",
		storyPic=3,
		background=3
	},
	{
		id=31,
		name="31.达成",
		story="与白玉堂达成协议，有盗帅相助，潜入杨府查找罪证还不是一帆风顺？",
		storyPic=1,
		background=1
	},
	{
		id=32,
		name="32.进展",
		story="好吧，出了点意外，与杨府死士们对峙了一番，还好本大人早有安排。",
		storyPic=2,
		background=2
	},
	{
		id=33,
		name="33.挑明",
		story="果然调查动作太大，让杨府众人警觉了。等等，陈圆圆，本官对你有了新的认识！",
		storyPic=3,
		background=3
	},
	{
		id=34,
		name="34.突变",
		story="大伙儿都摊牌了，那就决战了？诶？数万流民往这边过来了？不要吧，我好方……",
		storyPic=1,
		background=1
	},
	{
		id=35,
		name="35.挺身而出",
		story="这种时候，似乎应该是我出面的时候，知县不那么好当啊，就让我来安抚这帮流民吧！",
		storyPic=2,
		background=2
	},
	{
		id=36,
		name="36.镇定",
		story="数万流民都看着呢，要装着镇定点、硬气点，要让流民们有所依靠……所以，论演员的自我修养？",
		storyPic=3,
		background=3
	},
	{
		id=37,
		name="37.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=1,
		background=1
	},
	{
		id=38,
		name="38.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=2,
		background=2
	},
	{
		id=39,
		name="39.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=3,
		background=3
	},
	{
		id=40,
		name="40.入狱",
		story="没办法啊，禁军啊，人多啊，统领还那么厉害，牢狱之灾躲不掉了。",
		storyPic=1,
		background=1
	},
	{
		id=41,
		name="41.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=2,
		background=2
	},
	{
		id=42,
		name="42.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=3,
		background=3
	},
	{
		id=43,
		name="43.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=1,
		background=1
	},
	{
		id=44,
		name="44.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=2,
		background=2
	},
	{
		id=45,
		name="45.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=3,
		background=3
	},
	{
		id=46,
		name="46.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=1,
		background=1
	},
	{
		id=47,
		name="47.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=2,
		background=2
	},
	{
		id=48,
		name="48.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=3,
		background=3
	},
	{
		id=49,
		name="49.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=1,
		background=1
	},
	{
		id=50,
		name="50.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=2,
		background=2
	},
	{
		id=51,
		name="51.前因后果",
		story="平阳公主把事件始末说了出来，却原来，我已与几大势力打上了交道。",
		storyPic=3,
		background=3
	},
	{
		id=52,
		name="52.风波暂平",
		story="雨过天晴？风平浪静？先松一口气吧。公主殿下，我的诺言一定会实现！",
		storyPic=1,
		background=1
	},
	{
		id=53,
		name="53.升官",
		story="果然大难不死，必有后福！这不，升官了！普天同庆，普天同庆！",
		storyPic=2,
		background=2
	},
	{
		id=54,
		name="54.又是传闻",
		story="啥？闯王宝藏就藏在这一片儿？天，感觉要刮起一阵腥风血雨了！",
		storyPic=3,
		background=3
	},
	{
		id=55,
		name="55.一波未平",
		story="你们想要的经书已经让白玉堂拿走了……老白啊，对不住啊，你先担待着点儿啊！",
		storyPic=1,
		background=1
	},
	{
		id=56,
		name="56.风波不断",
		story="烦不烦啊，都说了没有……哎呦，美女你好！啥？找知府？知府不在！",
		storyPic=2,
		background=2
	},
	{
		id=57,
		name="57.余波",
		story="哎呦老白，这么多江湖人士都是为你而来啊。展护卫，上茶，上糕点！",
		storyPic=3,
		background=3
	},
	{
		id=58,
		name="58.安氏",
		story="安氏？掌门？武林高手啊！不好意思，经书送去公主府了，你们来晚了。",
		storyPic=1,
		background=1
	},
	{
		id=59,
		name="59.楚玉",
		story="多谢楚玉姑娘据实相告，楚玉姑娘真是貌美而心善，活菩萨啊！",
		storyPic=2,
		background=2
	},
	{
		id=60,
		name="60.武林大会",
		story="武林大会？西厂？多事之秋、风雨飘摇……姑娘这就走了？不知何时能再相见？",
		storyPic=3,
		background=3
	},
	{
		id=61,
		name="61.死人",
		story="大乱斗这就开始了？已经出现死者了？走，查案去！",
		storyPic=1,
		background=1
	},
	{
		id=62,
		name="62.劫狱",
		story="草菅人命的大喊仁义，贪赃枉法的标榜名誉，这个世界的三观都崩坏了。",
		storyPic=2,
		background=2
	},
	{
		id=63,
		name="63.突发事件",
		story="光天化日，射箭送信，我是要正面对上真正的凶人了。",
		storyPic=3,
		background=3
	},
	{
		id=64,
		name="64.清理",
		story="大破玄蜂寨，可以欢天喜地的查抄了。可是感觉有点不对……所以说，余千户你到底搜出了什么啊？",
		storyPic=1,
		background=1
	},
	{
		id=65,
		name="65.蹊跷",
		story="到处都透着蹊跷，尤其是商人陈圆圆，看来得好好调查一下了。",
		storyPic=2,
		background=2
	},
	{
		id=66,
		name="66.流民",
		story="最近很多灾民涌入，杨府在城南施粥，正好去看看，都是要关注的问题。",
		storyPic=3,
		background=3
	},
	{
		id=67,
		name="67.杨府晚宴",
		story="杨府设宴款待，这么好的调查机会当然要把握住了。等等，为什么一直灌我酒啊？",
		storyPic=1,
		background=1
	},
	{
		id=68,
		name="68.夜会",
		story="有黑衣人？这种事不重要啦，红拂姑娘在投怀送抱，哦不对，有要事禀报，我们在讨论严肃的事情。",
		storyPic=2,
		background=2
	},
	{
		id=69,
		name="69.旖旎",
		story="本官很生气，没看到本官……和红拂姑娘在床上探讨大事呢？推门而入想干嘛？",
		storyPic=3,
		background=3
	},
	{
		id=70,
		name="70.行动",
		story="杨府派了黑衣人，原来是去找佛经的。佛经还要这么郑重其事的找？其中必有蹊跷。",
		storyPic=1,
		background=1
	},
	{
		id=71,
		name="71.绸缪",
		story="要针对杨府做些布置了啊……红拂姑娘这么巧？看雨那？我陪你啊？",
		storyPic=2,
		background=2
	},
	{
		id=72,
		name="72.杀手",
		story="《佛说四十二章经》？左看右看也只是一本普通的佛经啊……干嘛推我？有杀手啊，有杀手？",
		storyPic=3,
		background=3
	},
	{
		id=73,
		name="73.宝藏传闻",
		story="听了个有些狗血的宝藏传闻，总感觉在哪里听过？也许吧。",
		storyPic=1,
		background=1
	},
	{
		id=74,
		name="74.进展",
		story="好吧，出了点意外，与杨府死士们对峙了一番，还好本大人早有安排。",
		storyPic=2,
		background=2
	},
	{
		id=75,
		name="75.挑明",
		story="果然调查动作太大，让杨府众人警觉了。等等，陈圆圆，本官对你有了新的认识！",
		storyPic=3,
		background=3
	},
	{
		id=76,
		name="76.突变",
		story="大伙儿都摊牌了，那就决战了？诶？数万流民往这边过来了？不要吧，我好方……",
		storyPic=1,
		background=1
	},
	{
		id=77,
		name="77.挺身而出",
		story="这种时候，似乎应该是我出面的时候，知县不那么好当啊，就让我来安抚这帮流民吧！",
		storyPic=2,
		background=2
	},
	{
		id=78,
		name="78.镇定",
		story="数万流民都看着呢，要装着镇定点、硬气点，要让流民们有所依靠……所以，论演员的自我修养？",
		storyPic=3,
		background=3
	},
	{
		id=79,
		name="79.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=1,
		background=1
	},
	{
		id=80,
		name="80.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=2,
		background=2
	},
	{
		id=81,
		name="81.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=3,
		background=3
	},
	{
		id=82,
		name="82.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=1,
		background=1
	},
	{
		id=83,
		name="83.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=2,
		background=2
	},
	{
		id=84,
		name="84.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=3,
		background=3
	},
	{
		id=85,
		name="85.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=1,
		background=1
	},
	{
		id=86,
		name="86.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=2,
		background=2
	},
	{
		id=87,
		name="87.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=3,
		background=3
	},
	{
		id=88,
		name="88.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=1,
		background=1
	},
	{
		id=89,
		name="89.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=2,
		background=2
	},
	{
		id=90,
		name="90.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=3,
		background=3
	},
	{
		id=91,
		name="91.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=1,
		background=1
	},
	{
		id=92,
		name="92.前因后果",
		story="把事件始末说了出来，却原来，我已与几大势力打上了交道。",
		storyPic=2,
		background=2
	},
	{
		id=93,
		name="93.风波暂平",
		story="雨过天晴？风平浪静？先松一口气吧。公主殿下，我的诺言一定会实现！",
		storyPic=3,
		background=3
	},
	{
		id=94,
		name="94.升官",
		story="果然大难不死，必有后福！这不，升官了！普天同庆，普天同庆！",
		storyPic=1,
		background=1
	},
	{
		id=95,
		name="95.又是传闻",
		story="啥？闯王宝藏就藏在这一片儿？天，感觉要刮起一阵腥风血雨了！",
		storyPic=2,
		background=2
	},
	{
		id=96,
		name="96.一波未平",
		story="你们想要的经书已经让白玉堂拿走了……老白啊，对不住啊，你先担待着点儿啊！",
		storyPic=3,
		background=3
	},
	{
		id=97,
		name="97.风波不断",
		story="烦不烦啊，都说了没有……哎呦，美女你好！啥？找知府？知府不在！",
		storyPic=1,
		background=1
	},
	{
		id=98,
		name="98.余波",
		story="哎呦老白，这么多江湖人士都是为你而来啊。展护卫，上茶，上糕点！",
		storyPic=2,
		background=2
	},
	{
		id=99,
		name="99.安氏",
		story="安氏？掌门？武林高手啊！不好意思，经书送去公主府了，你们来晚了。",
		storyPic=3,
		background=3
	},
	{
		id=100,
		name="100.楚玉",
		story="多谢楚玉姑娘据实相告，楚玉姑娘真是貌美而心善，活菩萨啊！",
		storyPic=1,
		background=1
	},
	{
		id=101,
		name="101.武林大会",
		story="武林大会？西厂？多事之秋、风雨飘摇……姑娘这就走了？不知何时能再相见？",
		storyPic=2,
		background=2
	},
	{
		id=102,
		name="102.死人",
		story="大乱斗这就开始了？已经出现死者了？走，查案去！",
		storyPic=3,
		background=3
	},
	{
		id=103,
		name="103.杀手",
		story="《佛说四十二章经》？左看右看也只是一本普通的佛经啊……干嘛推我？有杀手啊，有杀手？",
		storyPic=1,
		background=1
	},
	{
		id=104,
		name="104.宝藏传闻",
		story="听了个有些狗血的宝藏传闻，总感觉在哪里听过？也许吧。",
		storyPic=2,
		background=2
	},
	{
		id=105,
		name="105.进展",
		story="好吧，出了点意外，与杨府死士们对峙了一番，还好本大人早有安排。",
		storyPic=3,
		background=3
	},
	{
		id=106,
		name="106.挑明",
		story="果然调查动作太大，让杨府众人警觉了。等等，陈圆圆，本官对你有了新的认识！",
		storyPic=1,
		background=1
	},
	{
		id=107,
		name="107.突变",
		story="大伙儿都摊牌了，那就决战了？诶？数万流民往这边过来了？不要吧，我好方……",
		storyPic=2,
		background=2
	},
	{
		id=108,
		name="108.挺身而出",
		story="这种时候，似乎应该是我出面的时候，知县不那么好当啊，就让我来安抚这帮流民吧！",
		storyPic=3,
		background=3
	},
	{
		id=109,
		name="109.镇定",
		story="数万流民都看着呢，要装着镇定点、硬气点，要让流民们有所依靠……所以，论演员的自我修养？",
		storyPic=1,
		background=1
	},
	{
		id=110,
		name="110.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=2,
		background=2
	},
	{
		id=111,
		name="111.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=3,
		background=3
	},
	{
		id=112,
		name="112.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=1,
		background=1
	},
	{
		id=113,
		name="113.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=2,
		background=2
	},
	{
		id=114,
		name="114.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=3,
		background=3
	},
	{
		id=115,
		name="115.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=1,
		background=1
	},
	{
		id=116,
		name="116.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=2,
		background=2
	},
	{
		id=117,
		name="117.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=3,
		background=3
	},
	{
		id=118,
		name="118.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=1,
		background=1
	},
	{
		id=119,
		name="119.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=2,
		background=2
	},
	{
		id=120,
		name="120.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=3,
		background=3
	},
	{
		id=121,
		name="121.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=1,
		background=1
	},
	{
		id=122,
		name="122.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=2,
		background=2
	},
	{
		id=123,
		name="123.前因后果",
		story="平阳公主把事件始末说了出来，却原来，我已与几大势力打上了交道。",
		storyPic=3,
		background=3
	},
	{
		id=124,
		name="124.风波暂平",
		story="雨过天晴？风平浪静？先松一口气吧。公主殿下，我的诺言一定会实现！",
		storyPic=1,
		background=1
	},
	{
		id=125,
		name="125.升官",
		story="果然大难不死，必有后福！这不，升官了！普天同庆，普天同庆！",
		storyPic=2,
		background=2
	},
	{
		id=126,
		name="126.又是传闻",
		story="啥？闯王宝藏就藏在这一片儿？天，感觉要刮起一阵腥风血雨了！",
		storyPic=3,
		background=3
	},
	{
		id=127,
		name="127.一波未平",
		story="你们想要的经书已经让白玉堂拿走了……老白啊，对不住啊，你先担待着点儿啊！",
		storyPic=1,
		background=1
	},
	{
		id=128,
		name="128.风波不断",
		story="烦不烦啊，都说了没有……哎呦，美女你好！啥？找知府？知府不在！",
		storyPic=2,
		background=2
	},
	{
		id=129,
		name="129.余波",
		story="哎呦老白，这么多江湖人士都是为你而来啊。展护卫，上茶，上糕点！",
		storyPic=3,
		background=3
	},
	{
		id=130,
		name="130.安氏",
		story="安氏？掌门？武林高手啊！不好意思，经书送去公主府了，你们来晚了。",
		storyPic=1,
		background=1
	},
	{
		id=131,
		name="131.楚玉",
		story="多谢楚玉姑娘据实相告，楚玉姑娘真是貌美而心善，活菩萨啊！",
		storyPic=2,
		background=2
	},
	{
		id=132,
		name="132.武林大会",
		story="武林大会？西厂？多事之秋、风雨飘摇……姑娘这就走了？不知何时能再相见？",
		storyPic=3,
		background=3
	},
	{
		id=133,
		name="133.杀手",
		story="《佛说四十二章经》？左看右看也只是一本普通的佛经啊……干嘛推我？有杀手啊，有杀手？",
		storyPic=1,
		background=1
	},
	{
		id=134,
		name="134.宝藏传闻",
		story="听了个有些狗血的宝藏传闻，总感觉在哪里听过？也许吧。",
		storyPic=2,
		background=2
	},
	{
		id=135,
		name="135.进展",
		story="好吧，出了点意外，与杨府死士们对峙了一番，还好本大人早有安排。",
		storyPic=3,
		background=3
	},
	{
		id=136,
		name="136.挑明",
		story="果然调查动作太大，让杨府众人警觉了。等等，陈圆圆，本官对你有了新的认识！",
		storyPic=1,
		background=1
	},
	{
		id=137,
		name="137.突变",
		story="大伙儿都摊牌了，那就决战了？诶？数万流民往这边过来了？不要吧，我好方……",
		storyPic=2,
		background=2
	},
	{
		id=138,
		name="138.挺身而出",
		story="这种时候，似乎应该是我出面的时候，知县不那么好当啊，就让我来安抚这帮流民吧！",
		storyPic=3,
		background=3
	},
	{
		id=139,
		name="139.镇定",
		story="数万流民都看着呢，要装着镇定点、硬气点，要让流民们有所依靠……所以，论演员的自我修养？",
		storyPic=1,
		background=1
	},
	{
		id=140,
		name="140.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=2,
		background=2
	},
	{
		id=141,
		name="141.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=3,
		background=3
	},
	{
		id=142,
		name="142.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=1,
		background=1
	},
	{
		id=143,
		name="143.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=2,
		background=2
	},
	{
		id=144,
		name="144.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=3,
		background=3
	},
	{
		id=145,
		name="145.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=1,
		background=1
	},
	{
		id=146,
		name="146.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=2,
		background=2
	},
	{
		id=147,
		name="147.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=3,
		background=3
	},
	{
		id=148,
		name="148.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=1,
		background=1
	},
	{
		id=149,
		name="149.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=2,
		background=2
	},
	{
		id=150,
		name="150.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=3,
		background=3
	},
	{
		id=151,
		name="151.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=1,
		background=1
	},
	{
		id=152,
		name="152.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=2,
		background=2
	},
	{
		id=153,
		name="153.前因后果",
		story="平阳公主把事件始末说了出来，却原来，我已与几大势力打上了交道。",
		storyPic=3,
		background=3
	},
	{
		id=154,
		name="154.风波暂平",
		story="雨过天晴？风平浪静？先松一口气吧。公主殿下，我的诺言一定会实现！",
		storyPic=1,
		background=1
	},
	{
		id=155,
		name="155.升官",
		story="果然大难不死，必有后福！这不，升官了！普天同庆，普天同庆！",
		storyPic=2,
		background=2
	},
	{
		id=156,
		name="156.又是传闻",
		story="啥？闯王宝藏就藏在这一片儿？天，感觉要刮起一阵腥风血雨了！",
		storyPic=3,
		background=3
	},
	{
		id=157,
		name="157.一波未平",
		story="你们想要的经书已经让白玉堂拿走了……老白啊，对不住啊，你先担待着点儿啊！",
		storyPic=1,
		background=1
	},
	{
		id=158,
		name="158.风波不断",
		story="烦不烦啊，都说了没有……哎呦，美女你好！啥？找知府？知府不在！",
		storyPic=2,
		background=2
	},
	{
		id=159,
		name="159.余波",
		story="哎呦老白，这么多江湖人士都是为你而来啊。展护卫，上茶，上糕点！",
		storyPic=3,
		background=3
	},
	{
		id=160,
		name="160.安氏",
		story="安氏？掌门？武林高手啊！不好意思，经书送去公主府了，你们来晚了。",
		storyPic=1,
		background=1
	},
	{
		id=161,
		name="161.楚玉",
		story="多谢楚玉姑娘据实相告，楚玉姑娘真是貌美而心善，活菩萨啊！",
		storyPic=2,
		background=2
	},
	{
		id=162,
		name="162.武林大会",
		story="武林大会？西厂？多事之秋、风雨飘摇……姑娘这就走了？不知何时能再相见？",
		storyPic=3,
		background=3
	},
	{
		id=163,
		name="163.杀手",
		story="《佛说四十二章经》？左看右看也只是一本普通的佛经啊……干嘛推我？有杀手啊，有杀手？",
		storyPic=1,
		background=1
	},
	{
		id=164,
		name="164.宝藏传闻",
		story="听了个有些狗血的宝藏传闻，总感觉在哪里听过？也许吧。",
		storyPic=2,
		background=2
	},
	{
		id=165,
		name="165.进展",
		story="好吧，出了点意外，与杨府死士们对峙了一番，还好本大人早有安排。",
		storyPic=3,
		background=3
	},
	{
		id=166,
		name="166.挑明",
		story="果然调查动作太大，让杨府众人警觉了。等等，陈圆圆，本官对你有了新的认识！",
		storyPic=1,
		background=1
	},
	{
		id=167,
		name="167.突变",
		story="大伙儿都摊牌了，那就决战了？诶？数万流民往这边过来了？不要吧，我好方……",
		storyPic=2,
		background=2
	},
	{
		id=168,
		name="168.挺身而出",
		story="这种时候，似乎应该是我出面的时候，知县不那么好当啊，就让我来安抚这帮流民吧！",
		storyPic=3,
		background=3
	},
	{
		id=169,
		name="169.镇定",
		story="数万流民都看着呢，要装着镇定点、硬气点，要让流民们有所依靠……所以，论演员的自我修养？",
		storyPic=1,
		background=1
	},
	{
		id=170,
		name="170.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=2,
		background=2
	},
	{
		id=171,
		name="171.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=3,
		background=3
	},
	{
		id=172,
		name="172.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=1,
		background=1
	},
	{
		id=173,
		name="173.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=2,
		background=2
	},
	{
		id=174,
		name="174.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=3,
		background=3
	},
	{
		id=175,
		name="175.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=1,
		background=1
	},
	{
		id=176,
		name="176.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=2,
		background=2
	},
	{
		id=177,
		name="177.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=3,
		background=3
	},
	{
		id=178,
		name="178.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=1,
		background=1
	},
	{
		id=179,
		name="179.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=2,
		background=2
	},
	{
		id=180,
		name="180.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=3,
		background=3
	},
	{
		id=181,
		name="181.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=1,
		background=1
	},
	{
		id=182,
		name="182.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=2,
		background=2
	},
	{
		id=183,
		name="183.前因后果",
		story="平阳公主把事件始末说了出来，却原来，我已与几大势力打上了交道。",
		storyPic=3,
		background=3
	},
	{
		id=184,
		name="184.风波暂平",
		story="雨过天晴？风平浪静？先松一口气吧。公主殿下，我的诺言一定会实现！",
		storyPic=1,
		background=1
	},
	{
		id=185,
		name="185.升官",
		story="果然大难不死，必有后福！这不，升官了！普天同庆，普天同庆！",
		storyPic=2,
		background=2
	},
	{
		id=186,
		name="186.又是传闻",
		story="啥？闯王宝藏就藏在这一片儿？天，感觉要刮起一阵腥风血雨了！",
		storyPic=3,
		background=3
	},
	{
		id=187,
		name="187.一波未平",
		story="你们想要的经书已经让白玉堂拿走了……老白啊，对不住啊，你先担待着点儿啊！",
		storyPic=1,
		background=1
	},
	{
		id=188,
		name="188.当机立断",
		story="糟糕，办了件蠢事，居然把罪证送给了知府！当机立断，前往杨府……",
		storyPic=2,
		background=2
	},
	{
		id=189,
		name="189.对峙",
		story="与杨府众人交手、对峙、交手、对峙，嗯，应该稳操胜券了！",
		storyPic=3,
		background=3
	},
	{
		id=190,
		name="190.急转直下",
		story="事实狠狠的给了我一巴掌，一大堆禁军赶到，居然是来抓本知县的？",
		storyPic=1,
		background=1
	},
	{
		id=191,
		name="191.牢房里",
		story="身在牢房，啥也做不了。跟隔壁牢友聊聊天吧……这牢友挺有意思啊。",
		storyPic=2,
		background=2
	},
	{
		id=192,
		name="192.狄仁杰",
		story="啥？你是狄仁杰？失敬失敬、久仰久仰！别烦，我们还没寒暄完……哦，又是杀手啊，你好你好！",
		storyPic=3,
		background=3
	},
	{
		id=193,
		name="193.知府大人",
		story="知府大人英明神武，小小杀手毙于掌下……不对，知府大人是过来露个脸，说两句，告个别的。",
		storyPic=1,
		background=1
	},
	{
		id=194,
		name="194.越狱",
		story="什么？越狱？好啊好啊，这么刺激的事……一次就好。弟兄也一起？甚好甚好！",
		storyPic=2,
		background=2
	},
	{
		id=195,
		name="195.未遂",
		story="天不从人愿，让冉统领带人堵住了，好吧，把我抓了吧，别人都放了。",
		storyPic=3,
		background=3
	},
	{
		id=196,
		name="196.万民请命",
		story="上法场了，好没真实感。等等，很多人在喊着什么？是万民在为我请命，哦天！",
		storyPic=1,
		background=1
	},
	{
		id=197,
		name="197.北营统领",
		story="趁着官兵与百姓纠缠，众人上来搭救，我好感动……可是怎么突然多了这么多官兵？北营统领？我认栽！",
		storyPic=2,
		background=2
	},
	{
		id=198,
		name="198.千钧一发",
		story="没甚好说的了，可能要剧终了……冲锋？冲锋！玄甲军冲锋，危机时刻，平阳公主光芒闪耀！",
		storyPic=3,
		background=3
	},
	{
		id=199,
		name="199.公主威风",
		story="平阳公主才是主角吧？三言两语逼退两大统领、擒拿骊姬！",
		storyPic=1,
		background=1
	},
	{
		id=200,
		name="200.我不准",
		story="劫后余生，心里长舒了一口气……红拂呢？辞行？我不准！",
		storyPic=2,
		background=2
	}
}