return {
	{
		id=1,
		quality=1,
		description="武力增加1%",
		strengthPercent=100,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=2,
		quality=2,
		description="武力增加2%",
		strengthPercent=200,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=3,
		quality=3,
		description="武力增加3%",
		strengthPercent=300,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=4,
		quality=4,
		description="武力增加4%",
		strengthPercent=400,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=5,
		quality=5,
		description="武力增加5%",
		strengthPercent=500,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=6,
		quality=1,
		description="智力增加1%",
		strengthPercent=0,
		wisdomPercent=100,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=7,
		quality=2,
		description="智力增加2%",
		strengthPercent=0,
		wisdomPercent=200,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=8,
		quality=3,
		description="智力增加3%",
		strengthPercent=0,
		wisdomPercent=300,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=9,
		quality=4,
		description="智力增加4%",
		strengthPercent=0,
		wisdomPercent=400,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=10,
		quality=5,
		description="智力增加5%",
		strengthPercent=0,
		wisdomPercent=500,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=11,
		quality=1,
		description="魅力增加1%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=100,
		politicsPercent=0
	},
	{
		id=12,
		quality=2,
		description="魅力增加2%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=200,
		politicsPercent=0
	},
	{
		id=13,
		quality=3,
		description="魅力增加3%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=300,
		politicsPercent=0
	},
	{
		id=14,
		quality=4,
		description="魅力增加4%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=400,
		politicsPercent=0
	},
	{
		id=15,
		quality=5,
		description="魅力增加5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=500,
		politicsPercent=0
	},
	{
		id=16,
		quality=1,
		description="政治增加1%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=100
	},
	{
		id=17,
		quality=2,
		description="政治增加2%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=200
	},
	{
		id=18,
		quality=3,
		description="政治增加3%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=300
	},
	{
		id=19,
		quality=4,
		description="政治增加4%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=400
	},
	{
		id=20,
		quality=5,
		description="政治增加5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=500
	},
	{
		id=21,
		quality=1,
		description="武力增加0.5%",
		strengthPercent=50,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=22,
		quality=2,
		description="武力增加1.5%",
		strengthPercent=150,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=23,
		quality=3,
		description="武力增加2.5%",
		strengthPercent=250,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=24,
		quality=4,
		description="武力增加3.5%",
		strengthPercent=350,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=25,
		quality=5,
		description="武力增加4.5%",
		strengthPercent=450,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=26,
		quality=1,
		description="智力增加0.5%",
		strengthPercent=0,
		wisdomPercent=50,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=27,
		quality=2,
		description="智力增加1.5%",
		strengthPercent=0,
		wisdomPercent=150,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=28,
		quality=3,
		description="智力增加2.5%",
		strengthPercent=0,
		wisdomPercent=250,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=29,
		quality=4,
		description="智力增加3.5%",
		strengthPercent=0,
		wisdomPercent=350,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=30,
		quality=5,
		description="智力增加4.5%",
		strengthPercent=0,
		wisdomPercent=450,
		charmPercent=0,
		politicsPercent=0
	},
	{
		id=31,
		quality=1,
		description="魅力增加0.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=50,
		politicsPercent=0
	},
	{
		id=32,
		quality=2,
		description="魅力增加1.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=150,
		politicsPercent=0
	},
	{
		id=33,
		quality=3,
		description="魅力增加2.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=250,
		politicsPercent=0
	},
	{
		id=34,
		quality=4,
		description="魅力增加3.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=350,
		politicsPercent=0
	},
	{
		id=35,
		quality=5,
		description="魅力增加4.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=450,
		politicsPercent=0
	},
	{
		id=36,
		quality=1,
		description="政治增加0.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=50
	},
	{
		id=37,
		quality=2,
		description="政治增加1.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=150
	},
	{
		id=38,
		quality=3,
		description="政治增加2.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=250
	},
	{
		id=39,
		quality=4,
		description="政治增加3.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=350
	},
	{
		id=40,
		quality=5,
		description="政治增加4.5%",
		strengthPercent=0,
		wisdomPercent=0,
		charmPercent=0,
		politicsPercent=450
	}
}