---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/7/19 10:10
---
local cls = {
    res = "ui/systemUnlock"
}

function cls:init()
    UI.button(self.node, "BG/BtnClose", function()
        UI.close(self)
    end)
    UI.enable(self.node, "BG", false)
    self:show(true)
end

function cls:show(show)
    if show then
        message:send("C2S_showLockSystem", {}, function(msg)
            log(msg)
            UI.enable(self.node, "BG", show)
            if msg.ids and #msg.ids > 0 then
                local len = #msg.ids
                local parent = UI.child(self.node, "BG/S/V/C")
                local allConfig = config["systemOpen"]
                --table.sort(msg.ids,function(a, b)
                --    local aConfig = allConfig[a]
                --    local bConfig = allConfig[b]
                --    if aConfig.level < bConfig.level then
                --        return true
                --    elseif aConfig.level == bConfig.level then
                --        if aConfig.exam < bConfig.exam then
                --            return true
                --        elseif aConfig.exam == bConfig.exam then
                --            if aConfig.kid < bConfig.kid then
                --                return true
                --            elseif aConfig.kid == bConfig.kid then
                --                if aConfig.barrier <bConfig.barrier then
                --                    return true
                --                elseif aConfig.barrier == bConfig.barrier then
                --                    return false
                --                else
                --                    return false
                --                end
                --            else
                --                return false
                --            end
                --        else
                --            return false
                --        end
                --    else
                --        return false
                --    end
                --end)

                UI.cloneChild(parent, len)
                for i = 1, len do
                    local cfg = config["systemOpen"][msg.ids[i]]
                    --local data = {
                    --    title = config.name,
                    --    condi = "解锁条件：" .. config.unlock,
                    --    desc = "系统简介：" .. config.description
                    --}
                    --log(data)
                    UI.draw(parent:GetChild(i - 1), cfg)
                end
            else
                UI.showHint("所有功能均已开放")
                UI.close(self)
            end
        end)
    end
end

return cls