---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/8/17 15:30
---


local cls = {
    res = "ui/activityLoginTips"
}

function cls:init()

    self.activityNode = self.node:Find("Activity")
    self.btnNode = self.node:Find("BtnGo")

    UI.enable(self.node, false)
    UI.enableAll(self.activityNode, false)

    message:send("C2S_ReqLoginEventTips", {}, function(ret)
        log("++++++++++++++++++++++++")
        log(ret)
        UI.enable(self.node, true)
        UI.enableAll(self.node, true)
        self.activityList = ret.ids

        if #self.activityList > 0 then
            self:showActivity(self.activityList[1])
            count = 1
        else
            UI.close(self)
        end
    end)
end

function cls:showActivity(index)
    UI.enableOne(self.activityNode, index - 1)
    UI.enableOne(self.btnNode, index > 1 and 1 or 0)
    UI.button(self.node, "BtnGo", function()
        log(index)
        self:showSelect(index)
    end)
    UI.button(self.node, "BtnClose", function()
        self:showNext()
    end)

end

function cls:showSelect(index)
    self:showNext()
    if index == 1 then
        UI.openPage(UIPageName.TwoBeauty)
    elseif index == 2 then
        UI.openPage(UIPageName.PayReward)
    elseif index == 3 then
        UI.openPage(UIPageName.LimitReward)
    elseif index == 4 then
        UI.openPage(UIPageName.LifeLong)
    end
end

function cls:showNext()
    if count < #self.activityList then
        self:showActivity(self.activityList[count + 1])
        count = count + 1
    else
        UI.close(self)
    end
end

return cls