---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/8/11 17:09
---

local cls = {}

function cls:init()

end

function cls:registerBtn(btnNode,id)

end

function cls:unRegisterBtn(btnNode,id)

end

return cls